apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: config-service
    app.kubernetes.io/managed-by: Helm
  name: neo4j-nodeport-service
spec:
  ports:
  - name: default
    port: 27017
    protocol: TCP
    nodePort: 27017
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: config-service
  type: NodePort