from logging import INFO,DEBUG
NEO4J_SERVER_URL = "neo4j://10.10.1.146:7687"
NEO4J_SERVER_USERNAME = "neo4j"

NEO4J_SERVER_PASSWORD = "mySecretPassword"
GOOGLE_API_KEY = "AIzaSyCChUK1mpjVQE7eEc2GSeobACpSlNgqJcA"
LOG_LEVEL = INFO