from logging import INFO,DEBUG
NEO4J_SERVER_URL = "bolt://10.10.1.146:7687"
NEO4J_SERVER_USERNAME = "neo4j"
NEO4J_SERVER_PASSWORD = "neo4j"
GOOGLE_API_KEY = "AIzaSyCChUK1mpjVQE7eEc2GSeobACpSlNgqJcA"
LOG_LEVEL = INFO