# This ConfigMap gets passed to all core cluster members to configure them.
# Take note that some networking settings like internal hostname still get configured
# when the pod starts, but most non-networking specific configs can be tailored here.
#
# When your pods start, you will inherit the config in common-configmap.yaml, so you don't
# need to repeat any of that here, just focus on overrides that are different than what's there.
apiVersion: v1
kind: ConfigMap
metadata:
  name: "mygraph-neo4j-externally-addressable-config"
data:
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_dbms_mode: CORE
  NEO4JLABS_PLUGINS: '["graph-data-science"]'
  mygraph_neo4j_core_0_NEO4J_dbms_default__advertised__address: 10.10.1.146
  mygraph_neo4j_core_0_NEO4J_dbms_connector_bolt_advertised__address: 10.10.1.146:30001
  mygraph_neo4j_core_0_NEO4J_dbms_connector_http_advertised__address: 10.10.1.146:30002
  mygraph_neo4j_core_0_NEO4J_dbms_connector_https_advertised__address: 10.10.1.146:30003
  mygraph_neo4j_core_0_NEO4J_dbms_routing_enabled: "true"

  mygraph_neo4j_core_1_NEO4J_dbms_default__advertised__address: 10.10.1.146
  mygraph_neo4j_core_1_NEO4J_dbms_connector_bolt_advertised__address: 10.10.1.146:30004
  mygraph_neo4j_core_1_NEO4J_dbms_connector_http_advertised__address: 10.10.1.146:30005
  mygraph_neo4j_core_1_NEO4J_dbms_connector_https_advertised__address: 10.10.1.146:30006
  mygraph_neo4j_core_1_NEO4J_dbms_routing_enabled: "true"
  
  mygraph_neo4j_core_2_NEO4J_dbms_default__advertised__address: 10.10.1.146
  mygraph_neo4j_core_2_NEO4J_dbms_connector_bolt_advertised__address: 10.10.1.146:30007
  mygraph_neo4j_core_2_NEO4J_dbms_connector_http_advertised__address: 10.10.1.146:30008
  mygraph_neo4j_core_2_NEO4J_dbms_connector_https_advertised__address: 10.10.1.146:30009
  mygraph_neo4j_core_2_NEO4J_dbms_routing_enabled: "true"

  mygraph_neo4j_core_3_NEO4J_dbms_default__advertised__address: 10.10.1.146
  mygraph_neo4j_core_3_NEO4J_dbms_connector_bolt_advertised__address: 10.10.1.146:30010
  mygraph_neo4j_core_3_NEO4J_dbms_connector_http_advertised__address: 10.10.1.146:30011
  mygraph_neo4j_core_3_NEO4J_dbms_connector_https_advertised__address: 10.10.1.146:30012
  mygraph_neo4j_core_3_NEO4J_dbms_routing_enabled: "true"

  mygraph_neo4j_core_4_NEO4J_dbms_default__advertised__address: 10.10.1.146
  mygraph_neo4j_core_4_NEO4J_dbms_connector_bolt_advertised__address: 10.10.1.146:30013
  mygraph_neo4j_core_4_NEO4J_dbms_connector_http_advertised__address: 10.10.1.146:30014
  mygraph_neo4j_core_4_NEO4J_dbms_connector_https_advertised__address: 10.10.1.146:30015
  mygraph_neo4j_core_4_NEO4J_dbms_routing_enabled: "true"