apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: navneetraju/metadata_store:config-service
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
        

---

apiVersion: v1
kind: Service
metadata:
  name: config-service-service
spec:
  selector:
    app: config-service
  ports:
  - port: 80
    nodePort: 8080
  type: NodePort