apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: neo4j
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-0
  name: mygraph-neo4j-external-0
spec:
  loadBalancerIP: 127.0.0.1
  externalTrafficPolicy: Local
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: https
    port: 7473
    protocol: TCP
    targetPort: 7473
  selector:
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-0
  sessionAffinity: None
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: neo4j
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-1
  name: mygraph-neo4j-external-1
spec:
  loadBalancerIP: 127.0.0.1
  externalTrafficPolicy: Local
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: https
    port: 7473
    protocol: TCP
    targetPort: 7473
  selector:
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-1
  sessionAffinity: None
  type: LoadBalancer

--- 

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: neo4j
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-2
  name: mygraph-neo4j-external-2
spec:
  loadBalancerIP: 127.0.0.1
  externalTrafficPolicy: Local
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: https
    port: 7473
    protocol: TCP
    targetPort: 7473
  selector:
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-2
  sessionAffinity: None
  type: LoadBalancer
