apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-react-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metadata-react-app
  template:
    metadata:
      labels:
        app: metadata-react-app
    spec:
      containers:
      - name: metadata-react-app
        image: navneetraju/metadata_store:metadata_react_app
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: metadata-react-app-service
spec:
  selector:
    app: metadata-react-app
  ports:
  - port: 80
    nodePort: 80
  type: NodePort