apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: neo4j
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-0
  name: mygraph-neo4j-external-0
spec:
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    nodePort: 30001
  - name: http
    port: 7474
    protocol: TCP
    nodePort: 30002
  - name: https
    port: 7473
    protocol: TCP
    nodePort: 30003
  selector:
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-0
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: neo4j
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-1
  name: mygraph-neo4j-external-1
spec:
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    nodePort: 30004
  - name: http
    port: 7474
    protocol: TCP
    nodePort: 30005
  - name: https
    port: 7473
    protocol: TCP
    nodePort: 30006
  selector:
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-1
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: neo4j
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-2
  name: mygraph-neo4j-external-2
spec:
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    nodePort: 30007
  - name: http
    port: 7474
    protocol: TCP
    nodePort: 30008
  - name: https
    port: 7473
    protocol: TCP
    nodePort: 30009
  selector:
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-2
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: neo4j
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-3
  name: mygraph-neo4j-external-3
spec:
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    nodePort: 30010
  - name: http
    port: 7474
    protocol: TCP
    nodePort: 30011
  - name: https
    port: 7473
    protocol: TCP
    nodePort: 30012
  selector:
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-3
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: neo4j
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-4
  name: mygraph-neo4j-external-4
spec:
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    nodePort: 30013
  - name: http
    port: 7474
    protocol: TCP
    nodePort: 30014
  - name: https
    port: 7473
    protocol: TCP
    nodePort: 30015
  selector:
    statefulset.kubernetes.io/pod-name: mygraph-neo4j-core-4
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
    app.kubernetes.io/managed-by: Helm
  name: neo4j-nodeport-service
spec:
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    nodePort: 7687
  - name: http
    port: 7474
    protocol: TCP
    nodePort: 7474
  - name: https
    port: 7473
    protocol: TCP
    nodePort: 7473
  selector:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
  type: NodePort